# Generated by Django 4.2.6 on 2023-10-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLLeMensAPI', '0004_approvedfiletyps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenAIToken',
        ),
    ]
