version: '3'
services:
  db_load:
    build:
      context: .
      dockerfile: create-db.Dockerfile
    volumes:
      - type: bind
        source: ./../CLLeMensWebServer
        target: /db

  db_dump:
    build:
      context: .
      dockerfile: dump-db.Dockerfile
    volumes:
      - type: bind
        source: ./../CLLeMensWebServer
        target: /db

  localtunnel_service:
    build:
      context: .
      dockerfile: localtunnel.Dockerfile
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    ports:
      - "8000:8000"
    command: /bin/sh -c "chmod +x /usr/src/app/run_localtunnel_and_update_lambda.sh && /usr/src/app/run_localtunnel_and_update_lambda.sh"